// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: location-pkg-models.proto

package location_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationUuid  []byte                 `protobuf:"bytes,1,opt,name=location_uuid,json=locationUuid,proto3" json:"location_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Lang          []string               `protobuf:"bytes,4,rep,name=lang,proto3" json:"lang,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLocationUuid() []byte {
	if x != nil {
		return x.LocationUuid
	}
	return nil
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetLang() []string {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *Location) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_location_pkg_models_proto protoreflect.FileDescriptor

const file_location_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x19location-pkg-models.proto\x12\x06models\"\xa1\x01\n" +
	"\bLocation\x12#\n" +
	"\rlocation_uuid\x18\x01 \x01(\fR\flocationUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04lang\x18\x04 \x03(\tR\x04lang\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04cityB\x18Z\x16protocols/location-pkgb\x06proto3"

var (
	file_location_pkg_models_proto_rawDescOnce sync.Once
	file_location_pkg_models_proto_rawDescData []byte
)

func file_location_pkg_models_proto_rawDescGZIP() []byte {
	file_location_pkg_models_proto_rawDescOnce.Do(func() {
		file_location_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_pkg_models_proto_rawDesc), len(file_location_pkg_models_proto_rawDesc)))
	})
	return file_location_pkg_models_proto_rawDescData
}

var file_location_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_location_pkg_models_proto_goTypes = []any{
	(*Location)(nil), // 0: models.Location
}
var file_location_pkg_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_pkg_models_proto_init() }
func file_location_pkg_models_proto_init() {
	if File_location_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_pkg_models_proto_rawDesc), len(file_location_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_pkg_models_proto_goTypes,
		DependencyIndexes: file_location_pkg_models_proto_depIdxs,
		MessageInfos:      file_location_pkg_models_proto_msgTypes,
	}.Build()
	File_location_pkg_models_proto = out.File
	file_location_pkg_models_proto_goTypes = nil
	file_location_pkg_models_proto_depIdxs = nil
}
