// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: location-pkg-service.proto

package location_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationUuid  []byte                 `protobuf:"bytes,1,opt,name=location_uuid,json=locationUuid,proto3" json:"location_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationGetReq) Reset() {
	*x = LocationGetReq{}
	mi := &file_location_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationGetReq) ProtoMessage() {}

func (x *LocationGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationGetReq.ProtoReflect.Descriptor instead.
func (*LocationGetReq) Descriptor() ([]byte, []int) {
	return file_location_pkg_service_proto_rawDescGZIP(), []int{0}
}

func (x *LocationGetReq) GetLocationUuid() []byte {
	if x != nil {
		return x.LocationUuid
	}
	return nil
}

type LocationDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationUuid  []byte                 `protobuf:"bytes,1,opt,name=location_uuid,json=locationUuid,proto3" json:"location_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationDeleteReq) Reset() {
	*x = LocationDeleteReq{}
	mi := &file_location_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationDeleteReq) ProtoMessage() {}

func (x *LocationDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationDeleteReq.ProtoReflect.Descriptor instead.
func (*LocationDeleteReq) Descriptor() ([]byte, []int) {
	return file_location_pkg_service_proto_rawDescGZIP(), []int{1}
}

func (x *LocationDeleteReq) GetLocationUuid() []byte {
	if x != nil {
		return x.LocationUuid
	}
	return nil
}

type EmptyLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyLocation) Reset() {
	*x = EmptyLocation{}
	mi := &file_location_pkg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyLocation) ProtoMessage() {}

func (x *EmptyLocation) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyLocation.ProtoReflect.Descriptor instead.
func (*EmptyLocation) Descriptor() ([]byte, []int) {
	return file_location_pkg_service_proto_rawDescGZIP(), []int{2}
}

var File_location_pkg_service_proto protoreflect.FileDescriptor

const file_location_pkg_service_proto_rawDesc = "" +
	"\n" +
	"\x1alocation-pkg-service.proto\x12\x06models\x1a\x19location-pkg-models.proto\"5\n" +
	"\x0eLocationGetReq\x12#\n" +
	"\rlocation_uuid\x18\x01 \x01(\fR\flocationUuid\"8\n" +
	"\x11LocationDeleteReq\x12#\n" +
	"\rlocation_uuid\x18\x01 \x01(\fR\flocationUuid\"\x0f\n" +
	"\rEmptyLocation2\x94\x02\n" +
	"\x0flocationService\x12A\n" +
	"\x16CreateOrUpdateLocation\x12\x10.models.Location\x1a\x15.models.EmptyLocation\x12:\n" +
	"\x0eLocationByUUID\x12\x16.models.LocationGetReq\x1a\x10.models.Location\x12>\n" +
	"\x0fGetAllLocations\x12\x15.models.EmptyLocation\x1a\x14.models.AllLocations\x12B\n" +
	"\x0eDeleteLocation\x12\x19.models.LocationDeleteReq\x1a\x15.models.EmptyLocationB\x18Z\x16protocols/location-pkgb\x06proto3"

var (
	file_location_pkg_service_proto_rawDescOnce sync.Once
	file_location_pkg_service_proto_rawDescData []byte
)

func file_location_pkg_service_proto_rawDescGZIP() []byte {
	file_location_pkg_service_proto_rawDescOnce.Do(func() {
		file_location_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_pkg_service_proto_rawDesc), len(file_location_pkg_service_proto_rawDesc)))
	})
	return file_location_pkg_service_proto_rawDescData
}

var file_location_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_location_pkg_service_proto_goTypes = []any{
	(*LocationGetReq)(nil),    // 0: models.LocationGetReq
	(*LocationDeleteReq)(nil), // 1: models.LocationDeleteReq
	(*EmptyLocation)(nil),     // 2: models.EmptyLocation
	(*Location)(nil),          // 3: models.Location
	(*AllLocations)(nil),      // 4: models.AllLocations
}
var file_location_pkg_service_proto_depIdxs = []int32{
	3, // 0: models.locationService.CreateOrUpdateLocation:input_type -> models.Location
	0, // 1: models.locationService.LocationByUUID:input_type -> models.LocationGetReq
	2, // 2: models.locationService.GetAllLocations:input_type -> models.EmptyLocation
	1, // 3: models.locationService.DeleteLocation:input_type -> models.LocationDeleteReq
	2, // 4: models.locationService.CreateOrUpdateLocation:output_type -> models.EmptyLocation
	3, // 5: models.locationService.LocationByUUID:output_type -> models.Location
	4, // 6: models.locationService.GetAllLocations:output_type -> models.AllLocations
	2, // 7: models.locationService.DeleteLocation:output_type -> models.EmptyLocation
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_pkg_service_proto_init() }
func file_location_pkg_service_proto_init() {
	if File_location_pkg_service_proto != nil {
		return
	}
	file_location_pkg_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_pkg_service_proto_rawDesc), len(file_location_pkg_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_pkg_service_proto_goTypes,
		DependencyIndexes: file_location_pkg_service_proto_depIdxs,
		MessageInfos:      file_location_pkg_service_proto_msgTypes,
	}.Build()
	File_location_pkg_service_proto = out.File
	file_location_pkg_service_proto_goTypes = nil
	file_location_pkg_service_proto_depIdxs = nil
}
