// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: location-pkg-models.proto

package location_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationUuid  []byte                 `protobuf:"bytes,1,opt,name=location_uuid,json=locationUuid,proto3" json:"location_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Lang          []string               `protobuf:"bytes,4,rep,name=lang,proto3" json:"lang,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Activeness    *Activeness            `protobuf:"bytes,7,opt,name=Activeness,proto3" json:"Activeness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLocationUuid() []byte {
	if x != nil {
		return x.LocationUuid
	}
	return nil
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetLang() []string {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *Location) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetActiveness() *Activeness {
	if x != nil {
		return x.Activeness
	}
	return nil
}

type Activeness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activeness) Reset() {
	*x = Activeness{}
	mi := &file_location_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activeness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activeness) ProtoMessage() {}

func (x *Activeness) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activeness.ProtoReflect.Descriptor instead.
func (*Activeness) Descriptor() ([]byte, []int) {
	return file_location_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *Activeness) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type AllLocations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllLocations) Reset() {
	*x = AllLocations{}
	mi := &file_location_pkg_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLocations) ProtoMessage() {}

func (x *AllLocations) ProtoReflect() protoreflect.Message {
	mi := &file_location_pkg_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLocations.ProtoReflect.Descriptor instead.
func (*AllLocations) Descriptor() ([]byte, []int) {
	return file_location_pkg_models_proto_rawDescGZIP(), []int{2}
}

func (x *AllLocations) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_location_pkg_models_proto protoreflect.FileDescriptor

const file_location_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x19location-pkg-models.proto\x12\x06models\"\xd5\x01\n" +
	"\bLocation\x12#\n" +
	"\rlocation_uuid\x18\x01 \x01(\fR\flocationUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04lang\x18\x04 \x03(\tR\x04lang\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x122\n" +
	"\n" +
	"Activeness\x18\a \x01(\v2\x12.models.ActivenessR\n" +
	"Activeness\")\n" +
	"\n" +
	"Activeness\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\">\n" +
	"\fAllLocations\x12.\n" +
	"\tlocations\x18\x01 \x03(\v2\x10.models.LocationR\tlocationsB\x18Z\x16protocols/location-pkgb\x06proto3"

var (
	file_location_pkg_models_proto_rawDescOnce sync.Once
	file_location_pkg_models_proto_rawDescData []byte
)

func file_location_pkg_models_proto_rawDescGZIP() []byte {
	file_location_pkg_models_proto_rawDescOnce.Do(func() {
		file_location_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_pkg_models_proto_rawDesc), len(file_location_pkg_models_proto_rawDesc)))
	})
	return file_location_pkg_models_proto_rawDescData
}

var file_location_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_location_pkg_models_proto_goTypes = []any{
	(*Location)(nil),     // 0: models.Location
	(*Activeness)(nil),   // 1: models.Activeness
	(*AllLocations)(nil), // 2: models.AllLocations
}
var file_location_pkg_models_proto_depIdxs = []int32{
	1, // 0: models.Location.Activeness:type_name -> models.Activeness
	0, // 1: models.AllLocations.locations:type_name -> models.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_location_pkg_models_proto_init() }
func file_location_pkg_models_proto_init() {
	if File_location_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_pkg_models_proto_rawDesc), len(file_location_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_pkg_models_proto_goTypes,
		DependencyIndexes: file_location_pkg_models_proto_depIdxs,
		MessageInfos:      file_location_pkg_models_proto_msgTypes,
	}.Build()
	File_location_pkg_models_proto = out.File
	file_location_pkg_models_proto_goTypes = nil
	file_location_pkg_models_proto_depIdxs = nil
}
